// Regenerates js/data/colos.js, which turns the data center code in
// Cloudflare's trace reply (e.g. "IST") into a city name.
//
// Cloudflare's status page lists every data center as a component named
// "City, Country - (CODE)". Run with `npm run update-colos`.

import { writeFile } from 'node:fs/promises';

const SOURCE = 'https://www.cloudflarestatus.com/api/v2/components.json';
const OUTPUT = new URL('../js/data/colos.js', import.meta.url);

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE} answered ${response.status}`);
const { components } = await response.json();

const cities = new Map();
for (const { name } of components) {
  const match = name.match(/^(.+?)\s+-\s+\(([A-Z]{3})\)$/);
  if (match) cities.set(match[2], match[1].split(',')[0].trim());
}
if (cities.size < 100) throw new Error(`Only found ${cities.size} data centers; the page format may have changed`);

const lines = [...cities]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([code, city]) => `  ${code}: ${JSON.stringify(city)},`);

await writeFile(
  OUTPUT,
  `// Cloudflare data center codes and their cities.
// Generated by scripts/update-colos.mjs. Don't edit by hand.
export default {
${lines.join('\n')}
};
`,
);
console.log(`Wrote ${cities.size} data centers to js/data/colos.js`);
